{% set name = "anthropic" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anthropic-{{ version }}.tar.gz
  sha256: 36184840bd33184697666d4f1ec951d78ef5da22e87d936cd3c04b611d84e93c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - pip
  run:
    - python >=3.8
    - httpx
    - requests
    - tokenizers
    - aiohttp

test:
  imports:
    - anthropic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/anthropics/anthropic-sdk-python
  license: MIT
  license_file: LICENSE
  summary: Library for accessing the anthropic API
  doc_url: https://console.anthropic.com/docs

extra:
  recipe-maintainers:
    - jenan-anthropic
    - mikelambert
    - siboehm
