{% set name = "anthropic" %}
{% set version = "0.88.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f4c7f6863d08c869913516f08d658fe53caaf8bcc4fbea3218df343d2a876c58

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0
  skip: true  # [py<39]

requirements:
  host:
    - python
    - hatch-fancy-pypi-readme
    - hatchling >=1.26.3
    - pip
  run:
    - python
    - httpx >=0.25.0,<1
    - pydantic >=1.9.0,<3
    - typing-extensions >=4.14,<5
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - sniffio
    - jiter >=0.4.0,<1
    - docstring_parser >=0.15,<1
  run_constrained:
    # aiohttp
    - httpx_aiohttp >=0.1.9
    # vertex
    - google-auth >=2,<3
    # From google-auth[requests]
    - requests >=2.20.0,<3.0.0
    # aws
    - boto3 >=1.28.57
    - botocore >=1.31.57
    # mcp
    - mcp >=1.0  # [py>=310]

# Not possible to load conftest.py, anaconda doesn't have http-snapshot
# in the main channel. Tests are disabled by this reason.
test:
  imports:
    - anthropic
    - anthropic.lib
    - anthropic.types
    - anthropic.resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/anthropics/anthropic-sdk-python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Library for accessing the anthropic API
  description: |
    The Anthropic Python SDK is a library for accessing the anthropic API.
    It provides a simple and intuitive interface for making requests to the API and handling responses.
    The SDK is designed to be easy to use and integrate into your existing Python projects.
  doc_url: https://platform.claude.com/docs/en/home
  dev_url: https://github.com/anthropics/anthropic-sdk-python

extra:
  recipe-maintainers:
    - jan-janssen
    - jenan-anthropic
    - mikelambert
    - moritzwilksch
    - siboehm
    - x5a
